---
title: "MMA dashboard"
output: 
  flexdashboard::flex_dashboard:
    vertical_layout: scroll
---

```{r setup, include=FALSE}
library(flexdashboard)
library(here)
library(tidyverse)
library(scales)
library(kableExtra)
library(janitor)
source(here("functions", "tables.R"))
source(here("functions", "plots.R"))
```

```{r data}
data_ufc <- readRDS(here("data", "data-ufc.rds"))
data_ufc_method_clean <- readRDS(here("data", "data-ufc-method-clean.rds"))
data_top_5_most_wins <- readRDS(here("data", "data-top-5-most-wins.rds"))
```

Column 
-----------------------------------------------------------------------

### UFC fighters with most wins

```{r}
table_top_5_wins(data_top_5_most_wins)
```

### How fights are won

```{r}
plot_victory_method(data_ufc_method_clean)
```

### What submission methods are most successful

```{r}
plot_submission_victories(data_ufc_method_clean)
```

### What knockout methods are most successful

```{r}
plot_knockout_victories(data_ufc_method_clean)
```

### Which round fights end

```{r}
plot_which_round_fights_end(data_ufc_method_clean)
```
